In [1]:
# 阶段二模块二作业：使用逻辑回归算法对鸢尾花数据集（或其他数据集）建模进行分类预测

In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

### 导入数据

In [3]:
X = load_iris().data

In [5]:
Y = load_iris().target

In [6]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### 切分数据集

In [8]:
Xtrain,Xtest,Ytrain,Ytest = train_test_split(X,Y,test_size = 0.3,random_state = 420)

### 数据集归一化

In [9]:
# 对训练集和测试集归一化
std = StandardScaler().fit(Xtrain)
Xtrain_ = std.transform(Xtrain)
Xtest_ = std.transform(Xtest)

In [12]:
Xtrain_,Xtest_

(array([[ 6.98926548e-01,  3.11391996e-01,  7.07721645e-01,
          9.95825472e-01],
        [ 4.65951032e-01, -1.67688798e+00,  3.19241130e-01,
          8.77215987e-02],
        [-1.16487758e+00,  9.04719988e-02, -1.29017814e+00,
         -1.33929877e+00],
        [ 1.51434085e+00,  3.11391996e-01,  1.20719659e+00,
          7.36367223e-01],
        [-1.16487758e+00, -1.30447998e-01, -1.34567536e+00,
         -1.33929877e+00],
        [ 3.49463274e-01,  7.53231990e-01,  8.74213294e-01,
          1.38501285e+00],
        [-4.65951032e-01,  9.74151987e-01, -1.40117258e+00,
         -1.33929877e+00],
        [-9.31902064e-01,  1.63691198e+00, -1.29017814e+00,
         -1.20956965e+00],
        [-1.16487758e-01, -5.72287992e-01,  7.07721645e-01,
          1.51474197e+00],
        [ 2.32975516e-01, -1.30447998e-01,  5.96727212e-01,
          7.36367223e-01],
        [-8.15414306e-01,  2.29967197e+00, -1.29017814e+00,
         -1.46902790e+00],
        [ 2.32975516e+00,  1.63691198e+00, 

### 在确定l2范式的情况下，使用网格搜索判断solver, C的最优组合

In [13]:
p = {
    'C':list(np.linspace(0.05,1,19)),
    'solver':['liblinear','sag','newton-cg','lbfgs'] 
}

model = LogisticRegression(penalty='l2',max_iter=10000)
GS = GridSearchCV(model,p,cv=5)
GS.fit(Xtrain_,Ytrain)

GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=10000),
             param_grid={'C': [0.05, 0.10277777777777777, 0.15555555555555556,
                               0.20833333333333331, 0.2611111111111111,
                               0.3138888888888889, 0.36666666666666664,
                               0.41944444444444445, 0.4722222222222222, 0.525,
                               0.5777777777777778, 0.6305555555555556,
                               0.6833333333333333, 0.7361111111111112,
                               0.788888888888889, 0.8416666666666667,
                               0.8944444444444445, 0.9472222222222223, 1.0],
                         'solver': ['liblinear', 'sag', 'newton-cg', 'lbfgs']})

In [14]:
GS.best_score_

0.9714285714285715

In [15]:
GS.best_params_

{'C': 0.41944444444444445, 'solver': 'sag'}

### 将最优的结果重新用来实例化模型，查看训练集和测试集下的分数

In [23]:
lr = LogisticRegression(penalty='l2',
                        C=GS.best_params_['C'],
                        solver=GS.best_params_['solver'],
                        )
lr.fit(Xtrain_,Ytrain)

LogisticRegression(C=0.41944444444444445, solver='sag')

In [26]:
lr.score(Xtrain_,Ytrain)

0.9714285714285714

In [29]:
lr.score(Xtest_,Ytest)

0.9555555555555556

### 计算精准度

In [34]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score,f1_score

In [36]:
confusion_matrix(Ytrain,lr.predict(Xtrain_))

array([[35,  0,  0],
       [ 0, 29,  1],
       [ 0,  2, 38]], dtype=int64)

In [28]:
# 精度
precision_score(Ytrain,lr.predict(Xtrain_),average='micro')

0.9714285714285714

In [30]:
precision_score(Ytest,lr.predict(Xtest_),average='micro')

0.9555555555555556